import type { Metadata } from "next";
import {Inter, Inter as FontSans} from "next/font/google"
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Full Stack FastAPI and Next.js",
  description: "Generated by create next app; Full Stack FastAPI and Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontBody.variable} ${fontSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
